// Generated by scripts/gen-registry.ts — do not edit by hand.
//
// DESIGN.md §9: adding a device is one folder under lib/devices/, and this file is the
// machine-written consequence. Invariant 2 holds because nothing here is authored.
// Regenerate with `npm run gen:registry`; the staleness test fails if this drifts.

import type { Device } from '../core/device'
import { device as device_roland_tr_1000 } from './roland-tr-1000/index'

/** Every device manifest, ordered by folder name (UTF-16 code unit). */
export const DEVICES: readonly Device[] = [
  device_roland_tr_1000,
]

/** Folder names, in the same order. Useful for error messages that name a source. */
export const DEVICE_FOLDERS: readonly string[] = [
  'roland-tr-1000',
]
