// Generated by scripts/gen-registry.ts — do not edit by hand.
//
// DESIGN.md §9: adding a device is one folder under lib/devices/, and this file is the
// machine-written consequence. Invariant 2 holds because nothing here is authored.
// Regenerate with `npm run gen:registry`; the staleness test fails if this drifts.

import type { Device } from '../core/device'
import { device as device_akai_mpc_live_iii } from './akai-mpc-live-iii/index'
import { device as device_akai_mpc_one_g2 } from './akai-mpc-one-g2/index'
import { device as device_akai_mpc_xl } from './akai-mpc-xl/index'
import { device as device_behringer_crave } from './behringer-crave/index'
import { device as device_elektron_digitakt_ii } from './elektron-digitakt-ii/index'
import { device as device_empress_zoia_euroburo } from './empress-zoia-euroburo/index'
import { device as device_intellijel_cascadia } from './intellijel-cascadia/index'
import { device as device_intellijel_metropolix } from './intellijel-metropolix/index'
import { device as device_korg_minilogue_xd } from './korg-minilogue-xd/index'
import { device as device_moog_dfam } from './moog-dfam/index'
import { device as device_moog_grandmother } from './moog-grandmother/index'
import { device as device_moog_matriarch } from './moog-matriarch/index'
import { device as device_moog_minitaur } from './moog-minitaur/index'
import { device as device_moog_mother_32 } from './moog-mother-32/index'
import { device as device_moog_subharmonicon } from './moog-subharmonicon/index'
import { device as device_moog_subsequent_37 } from './moog-subsequent-37/index'
import { device as device_polyend_tracker_mini } from './polyend-tracker-mini/index'
import { device as device_roland_mc_101 } from './roland-mc-101/index'
import { device as device_roland_tr_1000 } from './roland-tr-1000/index'
import { device as device_roland_tr_6s } from './roland-tr-6s/index'
import { device as device_roland_tr_8s } from './roland-tr-8s/index'
import { device as device_squarp_hapax } from './squarp-hapax/index'
import { device as device_synthstrom_deluge } from './synthstrom-deluge/index'
import { device as device_tascam_model_2400 } from './tascam-model-2400/index'
import { device as device_teenage_engineering_op_xy } from './teenage-engineering-op-xy/index'
import { device as device_torso_t1 } from './torso-t1/index'
import { device as device_zoom_livetrak_l_8 } from './zoom-livetrak-l-8/index'

/** Every device manifest, ordered by folder name (UTF-16 code unit). */
export const DEVICES: readonly Device[] = [
  device_akai_mpc_live_iii,
  device_akai_mpc_one_g2,
  device_akai_mpc_xl,
  device_behringer_crave,
  device_elektron_digitakt_ii,
  device_empress_zoia_euroburo,
  device_intellijel_cascadia,
  device_intellijel_metropolix,
  device_korg_minilogue_xd,
  device_moog_dfam,
  device_moog_grandmother,
  device_moog_matriarch,
  device_moog_minitaur,
  device_moog_mother_32,
  device_moog_subharmonicon,
  device_moog_subsequent_37,
  device_polyend_tracker_mini,
  device_roland_mc_101,
  device_roland_tr_1000,
  device_roland_tr_6s,
  device_roland_tr_8s,
  device_squarp_hapax,
  device_synthstrom_deluge,
  device_tascam_model_2400,
  device_teenage_engineering_op_xy,
  device_torso_t1,
  device_zoom_livetrak_l_8,
]

/** Folder names, in the same order. Useful for error messages that name a source. */
export const DEVICE_FOLDERS: readonly string[] = [
  'akai-mpc-live-iii',
  'akai-mpc-one-g2',
  'akai-mpc-xl',
  'behringer-crave',
  'elektron-digitakt-ii',
  'empress-zoia-euroburo',
  'intellijel-cascadia',
  'intellijel-metropolix',
  'korg-minilogue-xd',
  'moog-dfam',
  'moog-grandmother',
  'moog-matriarch',
  'moog-minitaur',
  'moog-mother-32',
  'moog-subharmonicon',
  'moog-subsequent-37',
  'polyend-tracker-mini',
  'roland-mc-101',
  'roland-tr-1000',
  'roland-tr-6s',
  'roland-tr-8s',
  'squarp-hapax',
  'synthstrom-deluge',
  'tascam-model-2400',
  'teenage-engineering-op-xy',
  'torso-t1',
  'zoom-livetrak-l-8',
]
