// Generated by scripts/gen-registry.ts — do not edit by hand.
//
// DESIGN.md §9: adding a device is one folder under lib/devices/, and this file is the
// machine-written consequence. Invariant 2 holds because nothing here is authored.
// Regenerate with `npm run gen:registry`; the staleness test fails if this drifts.

import type { Device } from '../core/device'
import { device as device_behringer_crave } from './behringer-crave/index'
import { device as device_elektron_digitakt_ii } from './elektron-digitakt-ii/index'
import { device as device_empress_zoia_euroburo } from './empress-zoia-euroburo/index'
import { device as device_intellijel_cascadia } from './intellijel-cascadia/index'
import { device as device_intellijel_metropolix } from './intellijel-metropolix/index'
import { device as device_korg_minilogue_xd } from './korg-minilogue-xd/index'
import { device as device_moog_subsequent_37 } from './moog-subsequent-37/index'
import { device as device_polyend_tracker_mini } from './polyend-tracker-mini/index'
import { device as device_roland_mc_101 } from './roland-mc-101/index'
import { device as device_roland_tr_1000 } from './roland-tr-1000/index'
import { device as device_roland_tr_8s } from './roland-tr-8s/index'
import { device as device_synthstrom_deluge } from './synthstrom-deluge/index'
import { device as device_tascam_model_2400 } from './tascam-model-2400/index'
import { device as device_zoom_livetrak_l_8 } from './zoom-livetrak-l-8/index'

/** Every device manifest, ordered by folder name (UTF-16 code unit). */
export const DEVICES: readonly Device[] = [
  device_behringer_crave,
  device_elektron_digitakt_ii,
  device_empress_zoia_euroburo,
  device_intellijel_cascadia,
  device_intellijel_metropolix,
  device_korg_minilogue_xd,
  device_moog_subsequent_37,
  device_polyend_tracker_mini,
  device_roland_mc_101,
  device_roland_tr_1000,
  device_roland_tr_8s,
  device_synthstrom_deluge,
  device_tascam_model_2400,
  device_zoom_livetrak_l_8,
]

/** Folder names, in the same order. Useful for error messages that name a source. */
export const DEVICE_FOLDERS: readonly string[] = [
  'behringer-crave',
  'elektron-digitakt-ii',
  'empress-zoia-euroburo',
  'intellijel-cascadia',
  'intellijel-metropolix',
  'korg-minilogue-xd',
  'moog-subsequent-37',
  'polyend-tracker-mini',
  'roland-mc-101',
  'roland-tr-1000',
  'roland-tr-8s',
  'synthstrom-deluge',
  'tascam-model-2400',
  'zoom-livetrak-l-8',
]
