import type { Metadata } from 'next'
import Link from 'next/link'
import { Footer } from '@/components/footer'
import { SITE_DESCRIPTION, SITE_NAME } from '@/lib/studio/site'
import { STUDIO_PATH } from '@/lib/studio/entry'
import { EXPLORE_PATH } from '@/lib/studio/catalogue'

/**
 * **The front door, which is no longer the studio.**
 *
 * `/` was the studio from build step 8, when the studio was the whole product and the site was
 * it plus two catalogues. It is now one of several things a reader might want and the only one
 * that asks for a rig before it does anything, so somebody arriving from a search result — and
 * almost everybody arrives from a search result, because all but one of the addresses here are
 * a page rather than the app — met a forty-six box tick-list before anything had said what the
 * tick-list was for. This page says it, and the studio is one of the ways out of it.
 *
 * **Prerendered, with no client boundary and nothing to decode.** It takes no `searchParams` and
 * is a function of nothing, which is exactly what the studio route stopped being at #99 and the
 * reason the two cannot share an address: one is a view of a request and one is a page.
 *
 * `canonical: '/'` is the layout's default and this is the route it was always describing; the
 * difference since the move is that there is now a page under it rather than a generated view
 * (#44). A permalinked guide is canonical to `/studio`, which `app/studio/page.tsx` states.
 *
 * **Its own markup is six links and two sentences.** No new stylesheet rule: the destinations
 * are the catalogue card every index on this site already uses, so this page cannot drift from
 * them visually, and the masthead is the masthead. What this page must not become is a second
 * navigation with its own ideas — the site nav is the one link set (#112), and this is a page
 * about what is behind those links rather than a copy of them.
 */

export const metadata: Metadata = {
  title: SITE_NAME,
  description: SITE_DESCRIPTION,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    url: '/',
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  twitter: { card: 'summary', title: SITE_NAME, description: SITE_DESCRIPTION },
}

/**
 * Where a reader can go, in the order the nav names them, so the two agree rather than each
 * having a view. The sentence under each one says what the thing *is*, in the words somebody
 * who has not used this would use: a device is a box, a direction is a song, a riff is one
 * figure, a sample is one sound.
 */
const DESTINATIONS: readonly { href: string; name: string; sub: string }[] = [
  {
    href: STUDIO_PATH,
    name: 'Studio',
    sub: 'Tick the boxes you own, choose a direction, and read the guide it resolves to — every part placed on a real voice, with real parameter values.',
  },
  {
    href: '/devices',
    name: 'Devices',
    sub: 'Every box in the library: what it can do, the settings this site knows for it, and the page in the manual each one came off.',
  },
  {
    href: '/directions',
    name: 'Directions',
    sub: 'The musical directions a guide can be built in, with the structure, harmony and parts each one asks for.',
  },
  {
    href: '/riffs',
    name: 'Riffs',
    sub: 'One figure at a time, named for the record it comes from: build the sound on the boxes you own and play it.',
  },
  {
    href: '/samples',
    name: 'Samples',
    sub: 'One sound at a time, recorded on your own rig, with the technique for getting it written out.',
  },
  {
    href: EXPLORE_PATH,
    name: 'Explore',
    sub: 'The factory patches a box ships, laid open: what each one is for, and a figure written for it where one exists.',
  },
]

export default function Page() {
  return (
    <main className="shell catalogue-page">
      <header className="masthead">
        <h1>{SITE_NAME}</h1>
        <p>{SITE_DESCRIPTION}</p>
        {/*
          Invariant 1, where a reader can see it, and in the masthead rather than under the list
          because it is part of what this is rather than a footnote to it. `.masthead p` is the
          register it wants — 13px, dim — and the same rule the line above it uses; a bare
          paragraph in the body renders at 15px in full-strength ink, which made the quietest
          claim on the page the loudest thing on it.
        */}
        <p>
          Nothing here is generated by a language model. Every setting is read off the manual for
          the box it is on, or marked as unverified until somebody reads it.
        </p>
      </header>

      <div className="catalogue-body">
        <ul className="catalogue-list">
          {DESTINATIONS.map((d) => (
            <li className="catalogue-item" key={d.href}>
              <Link className="catalogue-link" href={d.href}>
                <span className="catalogue-name">{d.name}</span>
                <span className="catalogue-sub">{d.sub}</span>
              </Link>
            </li>
          ))}
        </ul>
      </div>

      <Footer permalink={undefined} devices={[]} />
    </main>
  )
}
