/**
 * §7.1/#159/#78. What the bound costs on `industrial-techno` seed 9, the direction that has
 * always decided this number.
 *
 *   npm run bench:bound
 *
 * The whole registry, the cap lifted clear so the walk is the true node count rather than
 * whatever the cap would have stopped at. Three warmups discard the JIT's first look at the
 * search, then best-of-seven, because the quantity wanted is how fast this machine *can* run it
 * and a slower sample is only ever something else on the box.
 *
 * **This script used to assert its own node count and it was removed, deliberately.** The
 * constant said 9,006 while the real figure had reached 18,026, so `npm run bench:bound` threw
 * for anybody who ran it — through the TR-6S, #183's widening of the TR-8S's RC slot, and both
 * MPCs. Re-recording it was tried first and lasted under an hour: the OP-XY and the MPC One G2
 * landed and it was 26,841.
 *
 * That is the argument against having it here at all. The assertion could not tell the two cases
 * apart — **the library grew**, which is constant and fine, from **the traversal changed**, which
 * is the thing worth stopping for. It threw on the first and would have caught the second only by
 * accident. `test/search-bound.test.ts` pins the count per direction and per seed, it distinguishes
 * exactly that, and it runs in `npm run verify`; this was the same fact kept a second time in a
 * file nothing gates, which is why this copy was always the one that rotted.
 *
 * So the count is now **reported rather than asserted**. It prints beside the timing, which is what
 * a reader needs to know what was walked, and the gate keeps its own record honest. Anything that changes it has
 * changed the traversal and is a different search, which `test/search-bound.test.ts` is what
 * actually catches; this script asserts it so a timing can never be reported for a walk that
 * silently stopped being the same one.
 *
 * ## Recorded
 *
 * **1. Caching `crowdOverflow` and `idleDevices`** as scalars on `State`, maintained in
 * `apply`/`undo`, against recomputing both by a whole-rig scan at every node. 165,785 nodes
 * either side:
 *
 *     before   best 462.9 ms   median 464.9 ms
 *     after    best 393.4 ms   median 399.0 ms
 *
 * A 15% cut on the median. Same bound values at the same nodes, so the 168 exact counts in
 * `test/search-bound.test.ts` were untouched and both golden sets regenerated byte-identically.
 *
 * **2. A forced `crowdOverflow` lower bound — measured and rejected.** The idea: count the
 * remaining requests that must land, union the devices they can reach, and charge the shortfall
 * against those devices' remaining comfortable room. It is admissible and it is *vacuous here*.
 * Across all 168 searches the narrowest it ever came to biting was a slack of **38** — eight
 * requests that must land against 39 free comfortable voices — because the registry carries 72
 * comfortable voices and the widest direction asks nine parts of it. Zero nodes pruned on any
 * direction, and the timing sat inside run-to-run noise (391.8 ms against 394.1 ms median). A
 * Hall-style tightening, testing each subset of requests against its own reachable capacity
 * rather than one union, never got closer than a deficiency of −19. Dropped, and recorded here
 * so the next person to look at `crowdOverflow` does not re-derive it: the whole counting family
 * is dead until the directions roughly triple their part count or the rig shrinks to two boxes.
 *
 * **3. `liveFloor`'s one-step matching repair (#78).** Two remaining requests are routinely
 * costed against the *same voice*, and §4.2 will not let both have it; the floor now charges the
 * cheaper escape for all but one of them. This is a *tighter* bound rather than a cheaper one,
 * so unlike (1) the node count moves and moves enormously:
 *
 *     before   165,785 nodes   best 384.1 ms   median 388.0 ms
 *     after      8,309 nodes   best  19.6 ms   median  19.7 ms
 *
 * **20.0x the nodes, 19.6x the wall clock**, interleaved in one process against
 * `measureAssignWithoutMatchingRepair`, which is the same search with the repair switched off.
 * The whole matrix moved: `industrial-techno` 22.5x fewer nodes in total, `weave` 1.5x,
 * `major-key-electro` and `lydian-house` about 1.1x, `ambient-dub` not at all — its contested
 * voices are always free to break, so the repair is available and never costs anything.
 *
 * The answer did not move. Score, voices, recipes, sections, shortfalls and occupancy are
 * identical across all 168 shipped searches and across 16,000 generated ones
 * (`test/search-matching-floor.test.ts`), which is what a tighter admissible bound is supposed
 * to do and what had to be shown before the counts above could be re-recorded.
 *
 * **4. The Subharmonicon (#135) — not a bound change, a bigger library.** The precondition moved
 * 8,309 → 9,006 on this direction and seed, purely because there is a twentieth device to search
 * over. The two figures are not comparable as a speed measurement and are not offered as one;
 * this entry exists so the next reader knows why the constant below is not the number the (3)
 * block above ends on. The whole sweep's worst case, which is on seed 21 rather than seed 9, is
 * recorded in `test/search-symmetry.test.ts` and moved 8,309 → 9,507.
 */

import { assign, moodState } from '../lib/core/index'
import { DEVICES } from '../lib/devices/registry.generated'
import { industrialTechno } from '../lib/templates/index'

const WARMUPS = 3
const RUNS = 7
const LIFTED = 20_000_000

function once(): { ms: number; nodes: number } {
  const started = performance.now()
  const result = assign({
    devices: [...DEVICES],
    template: industrialTechno,
    mood: moodState({}),
    seed: 9,
    nodeCap: LIFTED,
  })
  const ms = performance.now() - started
  if (result.search.capped) throw new Error('capped, so this is not the worst case')
  return { ms, nodes: result.search.nodes }
}

for (let i = 0; i < WARMUPS; i++) once()

const times: number[] = []
let nodes = 0
for (let i = 0; i < RUNS; i++) {
  const run = once()
  times.push(run.ms)
  nodes = run.nodes
}



const sorted = [...times].sort((a, b) => a - b)
const best = sorted[0] as number
const median = sorted[(RUNS - 1) / 2] as number

console.log(`industrial-techno seed 9, ${String(nodes)} nodes, ${String(DEVICES.length)} devices`)
console.log(`runs    ${times.map((t) => t.toFixed(1)).join(', ')}`)
console.log(`best    ${best.toFixed(1)} ms`)
console.log(`median  ${median.toFixed(1)} ms`)
